baseURL = "http://localhost:5000"
disablePathToLower = true
languageCode = "en-us"
title = "Batista Harahap"
theme = "bhugo"
DefaultContentLanguage = "en"
disqusShortname = "bango29"
pygmentsCodeFences = true
pygmentsUseClasses = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = "/:slug"

[Author]
  name = "Batista Harahap"
  email = "b@tista.me"
  twitter = "tista"
  github = "tistaharahap"
  linkedin = "tista"
  soundcloud = "tistaharahap"

[Params]
  useHLJS = true
  logo = "/content/images/tista.jpg"
