[phases.setup]
cmds = [
  "wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.148.2/hugo_extended_0.148.2_linux-amd64.deb",
  "dpkg -i hugo.deb"
]

[ phases.build ]
cmds = ["hugo --minify"]

[ environment ]
HUGO_VERSION = "0.148.2"

[[ nixpacks.included_files ]]
paths = ["/public"]
