[ phases.build ]
cmds = [
  "wget -O /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.148.2/hugo_extended_0.148.2_linux-amd64.tar.gz",
  "tar -xzf /tmp/hugo.tar.gz -C /tmp",
  "chmod +x /tmp/hugo",
  "/tmp/hugo --minify"
]

[ environment ]
HUGO_VERSION = "0.148.2"

[[ nixpacks.included_files ]]
paths = ["/public"]
